x-env-variables: &env-variables
  DB_HOST: "db"
  DB_NAME: "transactions"
  DB_USER: "admin"
  DB_PASSWORD: "secure_password"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  REDIS_HOST: "redis"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: ./backend
    container_name: web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      <<: *env-variables

  celery:
    build: ./backend
    container_name: celery
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      <<: *env-variables

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    enable_ipv6: false