# Generated by Django 5.2.15 on 2026-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantlog',
            name='input_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='assistantlog',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
